project:
  type: website
  output-dir: docs

website:
  title: Project 2
  navbar:
    right:
      - icon: github
        href: https://math241s24.github.io/project-02-bookish_trends/
    left:
      - text: "Project"
        href: WriteUp.qmd
      - text: "Proposal"
        href: proposal.qmd
      - text: "Presentation"
        href: presentation.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto

